### ISSUE TITLE
Ctrl + click problems

### ISSUE THREAD

**Issue by ErezSha** [zackargyle/react-bash#21]
ctrl + L click jumps to URL line instead of clearing the terminal.
After that, every click on 'L' (without ctrl) does a clear and every 'C' clears the line.

**Comment by zackargyle** [comment]
Is this on Windows? Can't reproduce this issue on Mac.

**Comment by ErezSha** [comment]
OS: Linux - ubuntu 14.04
Browser: Chrome

Nevertheless, managing 'ctrl' in the State is wrong, because each event has the knowledge if ctrl is pressed.
