### ISSUE TITLE
add new command ?

### ISSUE THREAD

**Issue by hosseinmh** [zackargyle/react-bash#39]
hi 
is it possible to add bash command like npm or python ?
thanks

**Comment by zackargyle** [comment]
Hey! You can do whatever you'd like, but those might be more tricky. Python, for example, you could use something like [py.js](https://openerp-web-v7.readthedocs.io/en/stable/) under the hood to evaluate python expressions. NPM would be interesting, but you could potentially use the [unpkg](https://unpkg.com/#/) CDN to fetch dependencies or something.
