### ISSUE TITLE
Glitch when scrolling

### ISSUE THREAD

**Issue by winkler1** [zackargyle/react-bash#4]
When bottom of the terminal window is reached, the white background scrolls up-

![image](https://cloud.githubusercontent.com/assets/883896/15854387/8f0173de-2c77-11e6-8a5f-112da8cc7e03.png)

**Comment by zackargyle** [comment]
Looks like a bug for sure! Probably from when I added support for themes. I think all we need to do is add "overflowY: scroll" to the style object. Would you like to be the one to contribute? 😁

**Comment by zackargyle** [comment]
Fixed in #c2b214b3bdc0852cca52bfc61a1b2bb5fd98c889

**Comment by derekargueta** [comment]
@zackargyle are you sure this got fixed?.. Just tried it tonight 😬

![image](https://cloud.githubusercontent.com/assets/5253821/15924678/3cee4032-2de8-11e6-819e-266a9c556133.png)

**Comment by zackargyle** [comment]
Yup! Just hadn't pushed it to the gh-pages demo branch :) Pushed it now.
