### ISSUE TITLE
help doesn't seem to include newly added commands

### ISSUE THREAD

**Issue by alexander-morris** [zackargyle/react-bash#41]
Happy to build this out if you have any ideas :) 

We're working on an implementation to help demo some web3 concepts at web3-terminal.theblockchaininstitute.org. 

Really love your work! Feel free to email me at alex@theblockchaininstitute.org

**Comment by zackargyle** [comment]
You're totally right! I haven't worked on this project for a while, but it looks like all you'd need to do is:

1) In commands.js
```js
let newCommands = [];
export const setNewCommands = commands => {
  newCommands = commands;
};
```
Then add `...newCommands.map(value => ({ value }))` to the help command

2) In component.js: both componentDidMount and componentDidReceiveProps
```js
if (extensions) {
  setNewCommands(extension);
}
```

**Comment by alexander-morris** [comment]
D'oh! Thanks

Going to give this a try today!
