### ISSUE TITLE
Hitting `enter` with empty input shouldn't be an error

### ISSUE THREAD

**Issue by derekargueta** [zackargyle/react-bash#6]
Pressing enter without having any commands results in a "command not found" error. Should just start a new prompt, without error.

![image](https://cloud.githubusercontent.com/assets/5253821/15924604/d1bf4a36-2de7-11e6-9068-860f0a254c4e.png)

**Comment by zackargyle** [comment]
This [Commit](https://github.com/zackargyle/react-bash/commit/70a935b912d1110f7dd2c23ca6dc43c3de2fad55) fixes this. Thanks for the report!
