### ISSUE TITLE
ls doesn't respect -l option

### ISSUE THREAD

**Issue by nloveladyallen** [zackargyle/react-bash#9]

**Comment by zackargyle** [comment]
Good call. Added support in [this commit](https://github.com/zackargyle/react-bash/commit/2fadb081573c24eb0d7fba3ba5d0457e979d81e7).

**Comment by nloveladyallen** [comment]
Can you format the output like actual ls -l? As in showing permissions, file/directory/symlink status, etc.

**Comment by zackargyle** [comment]
That would be a feature request, since there is currently no such thing as `permissions` or `symlinks`. I'll look into it tho. :)
